"""paper_format_tables.py

Creates paper-style LaTeX tables (booktabs) from evaluation CSVs.
- Bold best-in-column values
- Adds caption + label

Default input files are the no-leak evaluation outputs.

Run:
  D:/majoproj/.venv/Scripts/python.exe paper_format_tables.py

Outputs:
  - paper_tables_noleak.tex
  - paper_tables_noleak.md (copy-paste friendly)
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import Dict, List

import pandas as pd


def _fmt(x: float | int | str | None, nd: int = 3) -> str:
    if x is None:
        return ""
    if isinstance(x, str):
        return x
    if isinstance(x, (int,)):
        return str(x)
    if isinstance(x, float):
        if math.isnan(x):
            return ""
        return f"{x:.{nd}f}"
    return str(x)


def _bold_if_best(value: float, best: float, tol: float = 1e-12) -> str:
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return ""
    if abs(value - best) <= tol:
        return f"\\textbf{{{_fmt(value)}}}"
    return _fmt(value)


def make_table(df: pd.DataFrame, caption: str, label: str) -> str:
    """Return LaTeX tabular with booktabs and bold best-in-column."""

    # Ensure numeric
    metric_cols = ["accuracy", "precision", "recall", "f1", "auc"]
    for c in metric_cols:
        df[c] = pd.to_numeric(df[c], errors="coerce")

    # Best values across models (max)
    best: Dict[str, float] = {c: float(df[c].max()) for c in metric_cols}

    cols = ["model", "accuracy", "precision", "recall", "f1", "auc"]

    lines: List[str] = []
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append(f"\\caption{{{caption}}}")
    lines.append(f"\\label{{{label}}}")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append("\\begin{tabular}{lccccc}")
    lines.append("\\toprule")
    lines.append("Model & Acc. & Prec. & Rec. & F1 & AUC \\")
    lines.append("\\midrule")

    # Sort for readability: AUC desc, then F1
    df_sorted = df.sort_values(["auc", "f1"], ascending=[False, False]).copy()

    for _, row in df_sorted.iterrows():
        model = str(row["model"])
        cells = [
            model,
            _bold_if_best(float(row["accuracy"]), best["accuracy"]),
            _bold_if_best(float(row["precision"]), best["precision"]),
            _bold_if_best(float(row["recall"]), best["recall"]),
            _bold_if_best(float(row["f1"]), best["f1"]),
            _bold_if_best(float(row["auc"]), best["auc"]),
        ]
        lines.append(" & ".join(cells) + " \\")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")

    return "\n".join(lines) + "\n"


def make_markdown_table(df: pd.DataFrame, title: str) -> str:
    df2 = df[["model", "accuracy", "precision", "recall", "f1", "auc"]].copy()
    for c in ["accuracy", "precision", "recall", "f1", "auc"]:
        df2[c] = pd.to_numeric(df2[c], errors="coerce").map(lambda x: _fmt(float(x)) if pd.notna(x) else "")
    df2 = df2.sort_values(["auc", "f1"], ascending=[False, False])
    return f"## {title}\n\n" + df2.to_markdown(index=False) + "\n"


def main() -> None:
    root = Path(".")

    cv_path = root / "paper_noleak_metrics_cv.csv"
    val_path = root / "paper_noleak_metrics_val.csv"

    if not cv_path.exists() or not val_path.exists():
        raise FileNotFoundError("Expected paper_noleak_metrics_cv.csv and paper_noleak_metrics_val.csv")

    df_cv = pd.read_csv(cv_path)
    df_val = pd.read_csv(val_path)

    tex_parts: List[str] = []
    tex_parts.append("% Auto-generated by paper_format_tables.py")
    tex_parts.append("% Requires: \\usepackage{booktabs}")
    tex_parts.append("% Optional: \\usepackage{caption}")
    tex_parts.append("")

    tex_parts.append(
        make_table(
            df_cv,
            caption="Performance comparison using 5-fold stratified cross-validation (no-leak feature set).",
            label="tab:metrics-cv-noleak",
        )
    )

    tex_parts.append(
        make_table(
            df_val,
            caption="Performance comparison on the held-out validation split (no-leak feature set).",
            label="tab:metrics-val-noleak",
        )
    )

    out_tex = root / "paper_tables_noleak.tex"
    out_tex.write_text("\n".join(tex_parts), encoding="utf-8")

    md_parts: List[str] = []
    md_parts.append("# Paper Tables (No-Leak)\n")
    md_parts.append(make_markdown_table(df_cv, "5-Fold Cross-Validation (pooled)") )
    md_parts.append(make_markdown_table(df_val, "Held-out Validation Split") )

    out_md = root / "paper_tables_noleak.md"
    out_md.write_text("\n".join(md_parts), encoding="utf-8")

    print(f"Wrote {out_tex}")
    print(f"Wrote {out_md}")


if __name__ == "__main__":
    main()
